(function(){
  class GameUI {
    constructor(){this.selection=Object.fromEntries(Object.keys(MBTI_CONFIG).map(k=>[k,0]));this.nodes={selectors:document.querySelector('#type-selectors'),total:document.querySelector('#total-count'),start:document.querySelector('#start-button'),startLabel:document.querySelector('#start-label'),reset:document.querySelector('#reset-button'),status:document.querySelector('#battle-status'),empty:document.querySelector('#empty-state'),winner:document.querySelector('#winner-overlay'),winnerType:document.querySelector('#winner-type'),replay:document.querySelector('#replay-button')};this.renderSelectors();this.update();}
    renderSelectors(){this.nodes.selectors.innerHTML=Object.entries(MBTI_CONFIG).map(([type,c])=>`<div class="type-row"><div class="type-info"><span class="mini-shape" style="--type-color:${c.color};--shape:${this.cssShape(c.shape)}"></span><div><strong>${type}</strong><small>${c.label}</small></div></div><div class="counter"><button data-type="${type}" data-change="-1" aria-label="${type}を減らす">−</button><span class="count" id="count-${type}">0</span><button data-type="${type}" data-change="1" aria-label="${type}を増やす">＋</button></div></div>`).join('');this.nodes.selectors.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const t=b.dataset.type,d=Number(b.dataset.change);this.selection[t]=Math.max(0,Math.min(GAME_CONFIG.maxPerType,this.selection[t]+d));this.update();});}
    cssShape(s){return s==='soft'?'circle(50%)':s==='diamond'?'polygon(50% 0,100% 50%,50% 100%,0 50%)':s==='star'?'polygon(50% 0,61% 34%,98% 35%,68% 56%,79% 92%,50% 70%,21% 92%,32% 56%,2% 35%,39% 34%)':'polygon(50% 0,65% 26%,93% 7%,76% 38%,100% 50%,74% 62%,93% 93%,62% 75%,50% 100%,38% 74%,7% 93%,25% 62%,0 50%,26% 38%,7% 7%,38% 26%)';}
    update(){let total=0;Object.entries(this.selection).forEach(([t,n])=>{document.querySelector(`#count-${t}`).textContent=n;total+=n;});this.nodes.total.textContent=total;this.nodes.start.disabled=total<2;}
    bindStart(fn){this.nodes.start.addEventListener('click',()=>fn({...this.selection}));this.nodes.replay.addEventListener('click',()=>fn({...this.selection}));}
    bindReset(fn){this.nodes.reset.addEventListener('click',()=>{Object.keys(this.selection).forEach(k=>this.selection[k]=0);this.update();fn?.();});}
    battleStarted(){this.nodes.empty.hidden=true;this.nodes.winner.hidden=true;this.nodes.status.classList.add('active');this.nodes.status.querySelector('span').textContent='BATTLE IN PROGRESS';this.nodes.startLabel.textContent='RESTART BATTLE';}
    battleEnded(type){this.nodes.status.classList.remove('active');this.nodes.status.querySelector('span').textContent='COMPLETE';this.nodes.winnerType.textContent=type||'DRAW';this.nodes.winner.hidden=false;}
    resetView(){this.nodes.empty.hidden=false;this.nodes.winner.hidden=true;this.nodes.status.classList.remove('active');this.nodes.status.querySelector('span').textContent='STANDBY';this.nodes.startLabel.textContent='START BATTLE';}
  }
  window.GameUI=GameUI;
})();
